first_app/urls.py
from django.urls import path
from . import views

# template tagging
app_name = 'first_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('form', views.form_page, name='form_page'),
    path('users', views.users_page, name='users_page'),
    path('help', views.help_page, name='help_page'),
    path('other', views.other_page, name='other_page'),
    path('relative', views.relative_page, name='relative_page'),
    path('register', views.register_page, name='register_page'),
    path('user_login', views.user_login_page, name='user_login_page'),
    path('user_logout', views.user_logout_page, name='user_logout_page'),
    path('special', views.special_page, name='special_page'),
]

udemy_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('first_app/', include('first_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class Users(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=128, unique=True)


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_app/forms.py
from django import forms
from django.core import validators
from . import models
from django.contrib.auth.models import User


class NewUserForm(forms.ModelForm):
    class Meta:
        model = models.Users
        fields = '__all__'


class NewUserProfileForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = models.User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = models.UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from . import models, forms


# Create your views here.

def index(request):
    test_dict = {'text': 'hello world', 'number': 100}
    webpages_ls = models.AccessRecord.objects.order_by('date')
    date_dict = {'access_records': webpages_ls}

    # Merge the two dictionaries
    context_dict = {**test_dict, **date_dict}
    return render(request, 'first_app/index.html', context=context_dict)


def help_page(request):
    my_dict = {'help_insert': '... thats too bad :('}
    return render(request, 'first_app/help.html', context=my_dict)


def users_page(request):
    users_ls = models.Users.objects.order_by('last_name')
    user_dict = {'users': users_ls}
    return render(request, 'first_app/users.html', context=user_dict)


def form_page(request):
    form = forms.NewUserForm()

    if request.method == 'POST':
        form = forms.NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return users_page(request)
        else:
            print('ERROR: Form is invalid!')

    return render(request, 'first_app/form.html', context={'form': form})


def other_page(request):
    return render(request, 'first_app/other.html')


def relative_page(request):
    return render(request, 'first_app/relative_url_templates.html')


def register_page(request):
    registered = False
    if request.method == 'POST':
        user_form = forms.NewUserProfileForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES.get('profile_pic')

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = forms.NewUserProfileForm()
        profile_form = forms.UserProfileInfoForm()

    return render(request, 'first_app/registration.html', context={'user_form': user_form,
                                                                   'profile_form': profile_form,
                                                                   'registered': registered})


def user_login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('Unsuccessful login attempt!')
            print(f'Username: {username} and password: {password}')
            return HttpResponse('Invalid Login Details!')
    else:
        return render(request, 'first_app/login.html', {})


@login_required
def user_logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special_page(request):
    return HttpResponse('You are logged in! :D')

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
             <div class="navbar-header">
                 <a class="navbar-brand" href="#">DjangoCourse</a>
             </div>
            <ul class="navbar-nav mr-auto">
                <li class="active"><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
                <li><a class="nav-link" href="{% url 'first_app:form_page' %}">Form</a></li>
                <li><a class="nav-link" href="{% url 'first_app:users_page' %}">Users</a></li>
                <li><a class="nav-link" href="{% url 'first_app:help_page' %}">Help</a></li>
                <li><a class="nav-link" href="{% url 'first_app:other_page' %}">Other</a></li>
                <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="nav-link" href="{% url 'first_app:register_page' %}">Register</a></li>

                {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="nav-link" href="{% url 'first_app:user_login_page' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="jumbotron">
            {% block body_block %}
    <!--    Anything outside of this will be inherited if you extend-->
            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/first_app/form.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
    {% block body_block %}
    <h1>Welcome!</h1>
    <h4>Please sign up here:</h4>
    <p></p>
    <div class="form-group">
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
    {% endblock %}

templates/first_app/help.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
    {% block body_block %}
        <h1>Welcome to the Help Page</h1>
        <h3>Do you need help? {{ help_insert }}</h3>
    {% endblock %}

templates/first_app/index.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
    {% load static %}
    {% block body_block %}
        <h1>Working a 9 to 5 job making you depressed?</h1>
        <img src="{% static "images/hungover_marshmallow_working.jpg" %}" alt="Image didn't load! :(" width="500">
        <p></p>
        <h3>Below are the companies that are responsible:</h3>
        <div class="table-hover table-striped">
            {% if access_records %}
                <table class="table">
                    <thead>
                        <th>Company</th>
                        <th>Date Accessed</th>
                    </thead>
                    {% for rec in access_records %}
                    <tr>
                        <td>{{ rec.name }}</td>
                        <td>{{ rec.date }}</td>
                    </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>NO ACCESS RECORDS FOUND!</p>
            {% endif %}
        </div>
        {{ text|cut:'world' }}
        {{ number|add:'99' }}
    {% endblock %}

templates/first_app/login.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
    {% load static %}
    {% block body_block %}
        <h1>Please Login</h1>
        <form method="post" action="{% url 'first_app:user_login_page' %}">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">
            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Enter Password">
            <input type="submit" name="" value="Login">
        </form>
    {% endblock %}

templates/first_app/other.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
    {% block body_block %}
        <h1>Welcome to the Other Page!</h1>
        <h2>This is an example of template inheritance! :D</h2>
    {% endblock %}

templates/first_app/registration.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
    {% load static %}
    {% block body_block %}
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register Here</h1>
            <h3>Fill out the form:</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}
    {% endblock %}

templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Relative URL Templates</title>
</head>
<body>
    <h1>Welcome to Relative URL Templates!</h1>
    <a href="{% url 'first_app:other_page' %}">The Other Page</a>
    <a href="{% url 'admin:index' %}">Admin</a>
    <a href="{% url 'index' %}">Index</a>
</body>
</html>

templates/first_app/users.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
    {% load static %}
    {% block body_block %}
        <h1>Users</h1>
        <h2>List of Active Users:</h2>
        <p></p>
        <div class="table-hover table-striped">
            {% if users %}
                <table class="table">
                    <thead>
                        <th>Last Name</th>
                        <th>First Name</th>
                        <th>Email</th>
                    </thead>
                    {% for usr in users %}
                    <tr>
                        <td>{{ usr.last_name }}</td>
                        <td>{{ usr.first_name }}</td>
                        <td>{{ usr.email }}</td>
                    </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>NO USERS RECORDS FOUND!</p>
            {% endif %}
        </div>
    {% endblock %}